import 'server-only'

/**
 * OpusPass entrance-pass ticket for manually-admitted guests, drawn on the
 * same portrait purple artwork as the WhatsApp-sent pass
 * (apps/opus_pass/src/app/entrance-pass/[token]/ticket.tsx). The static art
 * (background, ornaments, logo, "The wedding of", perforation) ships as a
 * pre-rasterized template PNG in public/entrance-pass/ — rebuilt from the
 * designer's SVG by apps/opus_pass/scripts/build-entrance-pass-template.mjs
 * (2600px-wide export for print) — and this module lays the per-guest data
 * over it as SVG text: couple names, date, venue, the SINGLE/DOUBLE party
 * pill and the real check-in QR.
 *
 * Deliberately identical content to the guest-facing pass: no guest name,
 * group tag, or time on the artwork — the ticket carries only what the
 * design carries, and identification happens by scanning the QR. All
 * geometry below is the opus_pass layout's 1300x1881 coordinate space;
 * keep the two in sync.
 */

export interface TicketFields {
  /** e.g. "Claudia & Daniel" — host-name override already applied. */
  coupleName: string
  /** Pre-formatted long date, e.g. "12 July 2026"; '' when the event has no date. */
  dateLabel: string
  /** Venue name + street address (no city), e.g. "Holy Family Basilica"; '' when unset. */
  venue: string
  /** City on its own — drawn on the ticket's second venue row; '' when unset. */
  city: string
  partySize: number
  /** data: URL PNG from generateEntryPassQrDataUrl(). */
  qrDataUrl: string
}

const TICKET_WIDTH = 1300
const TICKET_HEIGHT = 1881
const TEMPLATE_URL = '/entrance-pass/ticket-template.png'

const YELLOW = '#FFF24D'
const WHITE = '#FFFFFF'
const PURPLE = '#5C2D8D'

const NAME_BAND = { top: 486, height: 292, sidePad: 60 }
const DATE_ROW = { top: 770, height: 110 }
const VENUE_ROW = { top: 916, height: 190, sidePad: 60 }
const PILL = { top: 1227, height: 87 }
const QR_BOX = { top: 1386, size: 423, pad: 14 }

/** Tickets are only ever sold as Single or Double — those two words are
 *  the entire pill vocabulary. Anything above one is a Double; "Party of
 *  N" never appears on a ticket. */
function partySizeLabel(partySize: number): string {
  return partySize === 1 ? 'SINGLE' : 'DOUBLE'
}

/** Shrink a line to fit its slot — `em` is the font's rough average glyph
 *  width in em for the script it renders. */
function fitFontSize(text: string, maxWidth: number, base: number, em: number, floor: number): number {
  const fitted = Math.floor(maxWidth / (em * Math.max(1, text.length)))
  return Math.max(floor, Math.min(base, fitted))
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

const SERIF = `font-family="Playfair Display" font-weight="700"`

/**
 * Stamp the entrance-pass artwork with real event + guest data. Returns
 * SVG markup ready to render inline (dangerouslySetInnerHTML) or print;
 * the template PNG is referenced by URL rather than inlined so a
 * 500-guest import doesn't ship 500 copies of the same 160KB background.
 */
export function renderGuestTicketSvg(fields: TicketFields): string {
  // The only field NOT run through escapeXml below — it's interpolated
  // into an attribute, not text content, so it needs its own guard. It's
  // always machine-generated by generateEntryPassQrDataUrl() (our own
  // qrcode package output), never user input, but this catches any future
  // caller that accidentally passes something else through before it ever
  // reaches dangerouslySetInnerHTML on the client.
  if (!/^data:image\/png;base64,[A-Za-z0-9+/]+=*$/.test(fields.qrDataUrl)) {
    throw new Error('qrDataUrl is not a well-formed PNG data URL')
  }

  const contentWidth = TICKET_WIDTH - NAME_BAND.sidePad * 2
  const centerX = TICKET_WIDTH / 2

  // Couple names — Dancing Script yellow, centered in the band under
  // "The wedding of".
  const nameSize = fitFontSize(fields.coupleName, contentWidth, 160, 0.46, 64)
  const nameBaseline = Math.round(NAME_BAND.top + NAME_BAND.height / 2 + nameSize * 0.32)

  // Date only — the ticket never shows a time.
  const dateValue = fields.dateLabel || 'Date TBC'
  const dateSize = dateValue.length > 26 ? 46 : 56
  const dateBaseline = Math.round(DATE_ROW.top + DATE_ROW.height / 2 + dateSize * 0.35)

  // Venue — "Venue:" label + name/address, hand-wrapped onto at most two
  // centered lines (SVG text doesn't flow), then the city on its own line
  // beneath; the size drops until the venue value fits. The whole block is
  // vertically centered in the slot so 1, 2, or 3 lines all sit balanced.
  const venueValue = fields.venue || 'Venue TBC'
  const cityValue = fields.city || ''
  let venueSize = Math.max(venueValue.length, cityValue.length) > 40 ? 46 : 56
  let venueLines: string[]
  for (;;) {
    const charsPerLine = Math.floor(contentWidth / (venueSize * 0.52))
    const words = `Venue: ${venueValue}`.split(/\s+/)
    venueLines = ['']
    for (const word of words) {
      const line = venueLines[venueLines.length - 1]
      if (line && `${line} ${word}`.length > charsPerLine) venueLines.push(word)
      else venueLines[venueLines.length - 1] = line ? `${line} ${word}` : word
    }
    if (venueLines.length <= 2 || venueSize <= 34) break
    venueSize -= 6
  }
  if (cityValue) venueLines.push(cityValue)
  const venueLineHeight = venueSize * 1.3
  const venueMidY = VENUE_ROW.top + VENUE_ROW.height / 2

  // Party pill — white capsule, purple Playfair text, width approximated
  // from glyph count (no text measurement in string-land; Playfair bold
  // uppercase averages ~0.66em/glyph, verified against the designer's
  // SINGLE pill).
  const pillLabel = partySizeLabel(fields.partySize)
  const pillTextWidth = pillLabel.length * (52 * 0.66 + 3)
  const pillWidth = Math.round(pillTextWidth + 104)
  const pillBaseline = Math.round(PILL.top + PILL.height / 2 + 52 * 0.35)

  // The artwork's sample QR was white-on-purple; the real one sits on a
  // white card instead — inverted (light-on-dark) QRs fail on common
  // scanner stacks, and the card doubles as the quiet zone.
  const qrCardX = (TICKET_WIDTH - QR_BOX.size) / 2
  const qrInner = QR_BOX.size - QR_BOX.pad * 2

  return `<svg viewBox="0 0 ${TICKET_WIDTH} ${TICKET_HEIGHT}" xmlns="http://www.w3.org/2000/svg" role="img">
  <image href="${TEMPLATE_URL}" x="0" y="0" width="${TICKET_WIDTH}" height="${TICKET_HEIGHT}"/>
  <text x="${centerX}" y="${nameBaseline}" text-anchor="middle" font-family="Dancing Script" font-size="${nameSize}" fill="${YELLOW}">${escapeXml(fields.coupleName)}</text>
  <text x="${centerX}" y="${dateBaseline}" text-anchor="middle" ${SERIF} font-size="${dateSize}"><tspan fill="${YELLOW}">Date: </tspan><tspan fill="${WHITE}">${escapeXml(dateValue)}</tspan></text>
  ${venueLines
    .map((line, i) => {
      const label = i === 0 && line.startsWith('Venue: ')
      const body = label ? line.slice('Venue: '.length) : line
      const y = Math.round(venueMidY + (i - (venueLines.length - 1) / 2) * venueLineHeight + venueSize * 0.35)
      const prefix = label ? `<tspan fill="${YELLOW}">Venue: </tspan>` : ''
      return `<text x="${centerX}" y="${y}" text-anchor="middle" ${SERIF} font-size="${venueSize}">${prefix}<tspan fill="${WHITE}">${escapeXml(body)}</tspan></text>`
    })
    .join('\n  ')}
  <rect x="${centerX - pillWidth / 2}" y="${PILL.top}" width="${pillWidth}" height="${PILL.height}" rx="${PILL.height / 2}" fill="${WHITE}"/>
  <text x="${centerX}" y="${pillBaseline}" text-anchor="middle" ${SERIF} font-size="52" letter-spacing="3" fill="${PURPLE}">${escapeXml(pillLabel)}</text>
  <rect x="${qrCardX}" y="${QR_BOX.top}" width="${QR_BOX.size}" height="${QR_BOX.size}" rx="24" fill="${WHITE}"/>
  <image href="${fields.qrDataUrl}" x="${qrCardX + QR_BOX.pad}" y="${QR_BOX.top + QR_BOX.pad}" width="${qrInner}" height="${qrInner}"/>
</svg>`
}
