import 'server-only'
import { TICKET_TEMPLATE_SVG } from './ticket-template'

export interface TicketFields {
  partner1Name: string
  partner2Name: string
  /** Pre-formatted, e.g. "02 OCTOBER, 2026". */
  eventDateLabel: string
  /** Pre-formatted, e.g. "8:20PM" — omit the field entirely (pass ''). */
  eventTimeLabel: string
  /** Street/venue line, e.g. "Serena Hotel, 123 Independence Ave". */
  addressLine: string
  /** City line, e.g. "Dar es Salaam". */
  cityLine: string
  contactPhone: string
  guestName: string
  partySize: number
  groupTag: string | null
  /** data: URL PNG from generateEntryPassQrDataUrl(). */
  qrDataUrl: string
}

/** Matches the exact QR placeholder block in ticket-template.ts — see the
 * comment there for why this is safe to do with a non-greedy regex (the
 * block has exactly one level of nesting, all leaves, no other <g> pairs
 * inside it to confuse the "first double close" match). */
const QR_BLOCK_RE = /<g id="Qr_Code">[\s\S]*?<\/g>\s*<\/g>/

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/**
 * Stamps the base ticket template (ticket-template.ts) with real event +
 * guest data and swaps the decorative QR placeholder for the guest's real
 * entry-pass QR. Pure string substitution against known, exact placeholder
 * text in the source artwork — brittle if the template file changes, but
 * avoids a full SVG/DOM parser dependency for a one-off admin tool.
 */
export function renderGuestTicketSvg(fields: TicketFields): string {
  // The only field NOT run through escapeXml below — it's interpolated
  // into an attribute, not text content, so it needs its own guard. It's
  // always machine-generated by generateEntryPassQrDataUrl() (our own
  // qrcode package output), never user input, but this catches any future
  // caller that accidentally passes something else through before it ever
  // reaches dangerouslySetInnerHTML on the client.
  if (!/^data:image\/png;base64,[A-Za-z0-9+/]+=*$/.test(fields.qrDataUrl)) {
    throw new Error('qrDataUrl is not a well-formed PNG data URL')
  }

  // The embedded template starts with a leading newline + an
  // <?xml ...?> declaration (an artifact of the source file, harmless
  // when parsed by an HTML parser via dangerouslySetInnerHTML but not
  // valid as a standalone XML document) — strip both so the result is
  // clean either way.
  let svg = TICKET_TEMPLATE_SVG.replace(/^\s*<\?xml[^>]*\?>\s*/, '')

  // "Save the Date" fits an announcement, not a door ticket a guest
  // presents to be scanned in — relabeled to match actual use.
  svg = svg.replace('Save the Date', 'ENTRY PASS')

  svg = svg.replaceAll('CLAUDIA', escapeXml(fields.partner1Name.toUpperCase()))
  svg = svg.replaceAll('DANIEL', escapeXml(fields.partner2Name.toUpperCase()))
  svg = svg.replace('DATE: 02 OCTOBER, 2024', escapeXml(`DATE: ${fields.eventDateLabel}`))
  svg = svg.replace('TIME: 8:20PM', escapeXml(fields.eventTimeLabel ? `TIME: ${fields.eventTimeLabel}` : ''))
  svg = svg.replace('ADDRESS: 123 ANYWHERE ST.', escapeXml(`ADDRESS: ${fields.addressLine}`.slice(0, 40)))
  svg = svg.replace('ANY CITY', escapeXml(fields.cityLine.slice(0, 24)))
  svg = svg.replaceAll('+123-456-7890', escapeXml(fields.contactPhone))

  const partyLabel = fields.partySize > 1 ? `PARTY OF ${fields.partySize}` : 'ADMIT ONE'
  const subLabel = fields.groupTag ? `${partyLabel} · ${fields.groupTag.toUpperCase()}` : partyLabel

  // Replace the decorative QR placeholder with the real, guest-specific
  // entry-pass QR, plus the guest's name/party underneath it — the base
  // artwork has no name slot at all (it's a generic invitation design),
  // so this is new content, not a substitution.
  const qrReplacement = `<g id="Qr_Code">
    <image href="${fields.qrDataUrl}" x="484.6" y="61.72" width="82" height="80" preserveAspectRatio="xMidYMid meet"/>
  </g>
  <text class="st4" transform="translate(525.6 152)" text-anchor="middle"><tspan x="0" y="0">${escapeXml(fields.guestName.toUpperCase())}</tspan></text>
  <text class="st3" transform="translate(525.6 163)" text-anchor="middle" fill="#5c2d8c"><tspan x="0" y="0">${escapeXml(subLabel)}</tspan></text>`

  if (!QR_BLOCK_RE.test(svg)) {
    throw new Error('Ticket template QR placeholder not found — template artwork may have changed')
  }
  svg = svg.replace(QR_BLOCK_RE, qrReplacement)

  return svg
}
