import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        of: {
          primary: '#5B2D8E',
          medium: '#7B4FA2',
          light: '#C9A0DC',
          pale: '#F3EBF9',
          cream: '#faf7fc',
          white: '#FFFFFF',
          dark: '#2A1245',
          text: '#1E1028',
          muted: '#6B5A7A',
          border: 'rgba(91,45,142,0.12)',
          green: '#2D8E5B',
          gold: '#C4920A',
          coral: '#D85A30',
        },
        br: {
          bg: '#faf7fc',
          surface: '#faf7fc',
          'on-surface': '#1A0A2E',
          'on-surface-variant': '#6B5A7A',
          'primary-container': '#5B2D8E',
          'on-primary': '#ffffff',
          'surface-tint': '#7B4FA2',
          'tertiary-container': '#7B4FA2',
          'secondary-container': '#E5CFF0',
          'on-secondary-container': '#3D1B66',
          'tertiary-fixed': '#F3EBF9',
          'on-tertiary-fixed': '#2A1245',
          'surface-container-low': '#f6f1f9',
          'surface-container': '#f0e8f5',
          'surface-container-high': '#e8ddf0',
          'surface-container-highest': '#e0d4e8',
          'surface-container-lowest': '#ffffff',
          outline: '#8E7A9E',
          'outline-variant': '#D8C8E4',
          'primary-fixed': '#F0E2F7',
          'on-primary-container': '#C9A0DC',
          'on-tertiary-container': '#C9A0DC',
          error: '#ba1a1a',
          secondary: '#7B4FA2',
        },
      },
      fontFamily: {
        'dm-sans': ['DMSans'],
        'dm-sans-medium': ['DMSans-Medium'],
        'dm-sans-bold': ['DMSans-Bold'],
        playfair: ['PlayfairDisplay-SemiBold'],
        'playfair-bold': ['PlayfairDisplay-Bold'],
        'space-grotesk': ['SpaceGrotesk-Regular'],
        'space-grotesk-bold': ['SpaceGrotesk-Bold'],
        'work-sans': ['WorkSans-Regular'],
        'work-sans-medium': ['WorkSans-Medium'],
        'work-sans-semibold': ['WorkSans-SemiBold'],
        'work-sans-bold': ['WorkSans-Bold'],
      },
      borderRadius: {
        card: '16px',
        button: '14px',
        pill: '20px',
        input: '12px',
      },
    },
  },
  plugins: [],
};

export default config;
