-- OF-VND-0006: vendor code + full application snapshot
--
-- Adds two columns to public.vendors so admins can:
--   1. Reference a vendor by a short, human-readable code (VND-00001) instead
--      of the raw UUID (which currently renders as 32 hex chars in the
--      breadcrumb and is impossible to read aloud over the phone).
--   2. Review *every* answer the vendor entered during onboarding — including
--      style/personality, languages, awards, deposit %, cancellation policy,
--      hours, FAQs, etc. — fields the schema doesn't break out into columns
--      yet. Stored as a JSONB blob so the admin review page can render the
--      whole submission verbatim.

-- ---------------------------------------------------------------------------
-- 1. vendor_code: sequence-backed, prefixed, zero-padded to 5 digits
-- ---------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS public.vendor_code_seq
  AS BIGINT
  START WITH 10001
  INCREMENT BY 1
  MINVALUE 1
  NO MAXVALUE
  CACHE 1;

ALTER TABLE public.vendors
  ADD COLUMN IF NOT EXISTS vendor_code TEXT;

CREATE OR REPLACE FUNCTION public.generate_vendor_code()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  next_val BIGINT;
BEGIN
  next_val := nextval('public.vendor_code_seq');
  RETURN 'VND-' || lpad(next_val::TEXT, 5, '0');
END;
$$;

CREATE OR REPLACE FUNCTION public.set_vendor_code()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.vendor_code IS NULL OR NEW.vendor_code = '' THEN
    NEW.vendor_code := public.generate_vendor_code();
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_vendor_code_trigger ON public.vendors;
CREATE TRIGGER set_vendor_code_trigger
  BEFORE INSERT ON public.vendors
  FOR EACH ROW
  EXECUTE FUNCTION public.set_vendor_code();

-- Backfill existing rows in deterministic order so older vendors get lower
-- numbers. Done in a single statement using a CTE so we keep one nextval()
-- call per row.
WITH ordered AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS rn
  FROM public.vendors
  WHERE vendor_code IS NULL
)
UPDATE public.vendors v
SET vendor_code = public.generate_vendor_code()
FROM ordered o
WHERE v.id = o.id;

-- Now safe to enforce the constraint.
ALTER TABLE public.vendors
  ALTER COLUMN vendor_code SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_vendors_vendor_code_unique
  ON public.vendors(vendor_code);

COMMENT ON COLUMN public.vendors.vendor_code
  IS 'Short, human-readable vendor identifier — VND-XXXXX, generated by trigger on insert.';

-- ---------------------------------------------------------------------------
-- 2. application_snapshot: full onboarding draft for admin review
-- ---------------------------------------------------------------------------

ALTER TABLE public.vendors
  ADD COLUMN IF NOT EXISTS application_snapshot JSONB;

COMMENT ON COLUMN public.vendors.application_snapshot
  IS 'Full onboarding draft submitted at /onboard/review — captured verbatim so admin review can verify every answered field.';

-- Notify PostgREST so the schema cache picks up the new columns immediately.
NOTIFY pgrst, 'reload schema';
